#| code-fold: true
name: Fetch Google Scholar Publications

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  fetch-publications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Create package.json
        run: |
          echo '{
            "name": "scholar-fetch",
            "type": "module",
            "dependencies": {
              "node-fetch": "^3.3.2",
              "cheerio": "^1.0.0-rc.12"
            }
          }' > package.json
                    
      - name: Install dependencies
        run: npm install
          
      - name: Fetch publications
        run: node .github/scripts/fetch-publications.js
        env:
          SCHOLAR_ID: ${{ secrets.SCHOLAR_ID }}
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/publications.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update publications" && git push)          
